### PR TITLE
Style Improvements

### PR DESCRIPTION
**Pull request by GHLasse**
Several style improvements making the font size equal to other modules and allowing for different style options to be set, some shown below:
mm_lt_sample_veryshort
mm_lt_sample_short
mm_lt_sample_verylong

This fixes issue #5, #6 and #8 

Explanation of config variables:
- maximumEntries: maximum number of routes to show (default: 3)
- displayStationLength: number fo characters of the departure station for each transport mode to display. 0 means display all, -1 means don't show the departure station (default: 0)
- displayWalk: boolean if steps for walking should be shown (default: true)
- maxWalkTime: maximum time you are willing to walk between stations in minutes (default: 15)
- fade: boolean if a fade should be applied - same as for calendar module (default: true)
- fadePoint: percentage, where the fade should start. This should be a value between 0 and 1  - same as for calendar module (default: 0.3)
- animationSpeed: speed of update animation in seconds (default: 1)
- updateInterval: interval at which to request new routes from google api in minutes. Note that the module refreshes every 15seconds to always display an accurate estimate when you need to leave. (default: 5)
- language: language to display information in - german 'de' or english 'en' (default is same as defined in the main config file)
- units: units to use - metric or imperial (default is same as in the main config file)
- timeFormat: 24 or 12 hour clock for displaying the arrival time (default same as in the main config file)

### CODE REVIEW

**Comment by tombamber** [comment]
Hey, how do I install it with these new improvements?  I tried replacing the code with this code and the magic mirror did not display at all - just a black screen. 

Thanks :)

**Comment by GHLasse** [comment]
Can you pull the latest code from my site? I remember there was some minor bug in this merge request, but it should only really cause issues with a specific setting (which is being ignored because of the bug). Long story short I fixed it but forgot to set up another merge request... Could be the bug was more serious than I thought?

**Comment by GHLasse** [comment]
Seems like GitHub is linking to the latest version of my fork already. 
the essential change was in the main code:
`}else if (this.config.displayStationLength = 0){  ` changed to
`}else if (this.config.displayStationLength == 0){ `

Can you check that you set all the parameters required and that the error is not from another change you made? Can you send me the options you have set (you can leave the API key blank or as XXX - I will replace it with my own to test...)

**Comment by GHLasse** [comment]
Currently updating some things to make sure I didn't accidentally leave the repository in an old state. Therefore the latest version now probably doesn't work, as some translation strings are missing. Will upload the rest as soon as I have time again. (remind me if I stay silent for too long ;-) )

**Comment by GHLasse** [comment]
ok, that should be all :-D
even more options than before - check out the readme for details...

**Comment by tombamber** [comment]
Maybe I add the code wrong.  I simply replaced the code you wrote on this page with the original, is that correct?  

Is there an easier way to install it through the terminal?  I'm sorry, I'm quite new to this.

**Comment by GHLasse** [comment]
If you replaced ALL the original files with mine AND added the files I added AND updated your config file, then you should be fine :-D
You should be able to pull from my repository I would assume. Same procedure as what you did to get CFenners code running...
`cd MagicMirror`
`git clone https://github.com/GHLasse/MagicMirror-LocalTransport-Module.git modules/localtransport`

**Comment by CFenner** [comment]
Is this in a state I can simply merge it?

**Comment by GHLasse** [comment]
@CFenner yes, should be :-)

**Pull request merged**
